import { COMPANY } from "@/lib/company";

function val(v, fallback = "—") { return v === null || v === undefined || v === "" ? fallback : v; }
function num(v, digits = 2) { const n = Number(v); return Number.isFinite(n) ? new Intl.NumberFormat("tr-TR", { maximumFractionDigits: digits }).format(n) : "—"; }
function statusClass(v) { return String(v || "").toLowerCase().includes("ready") || String(v || "").toLowerCase().includes("uygun") ? "ok" : ""; }

export default function PublicRecord({ record, qrDataUrl }) {
  const components = Array.isArray(record.components) ? record.components : [];
  const materials = Array.isArray(record.materials) ? record.materials : [];
  return <div className="shell">
    <div className="topbar"><div className="brand"><div className="brandmark">AK</div><div className="brandtext"><strong>AÇILIM KUTU</strong><span>PPWR Packaging Compliance Portal</span></div></div><div className="lang"><button className="active">TR</button><button>EN</button></div></div>
    <section className="hero"><div><div className="eyebrow">Regulation (EU) 2025/40</div><h1>PPWR Uyumluluk / Compliance</h1><p>Ambalaj kimliği, izlenebilirlik, teknik dokümantasyon ve kontrollü belge erişimi için Açılım Kutu dijital PPWR kayıt ekranı.</p><div className="hero-meta"><div className="metric"><span>PPWR ID</span><strong>{val(record.ppwr_id)}</strong></div><div className="metric"><span>Declaration ID</span><strong>{val(record.declaration_id)}</strong></div><div className="metric"><span>Revision</span><strong>{val(record.revision_no)}</strong></div><div className="metric"><span>Last review</span><strong>{val(record.review_date)}</strong></div></div></div><div className="qrbox"><div className="qrinner"><img src={qrDataUrl} alt={`${record.public_code} QR`} /><b>{record.public_code}</b><small>Scan for digital record</small></div></div></section>
    <div className="grid">
      <section className="card"><h2>Firma Bilgileri / Company Information</h2><dl className="info"><dt>Ambalaj Üreticisi</dt><dd>{COMPANY.name}</dd><dt>Adres</dt><dd>{COMPANY.address}</dd><dt>E-posta</dt><dd>{COMPANY.email}</dd><dt>Telefon</dt><dd>{COMPANY.phone}</dd><dt>Müşteri</dt><dd>{val(record.customer)}</dd><dt>İthalatçı</dt><dd>{val(record.importer)}</dd></dl></section>
      <section className="card"><h2>Ambalaj Tanımı / Packaging Identification</h2><dl className="info"><dt>Açılım İş Kodu</dt><dd>{val(record.job_code)}</dd><dt>Müşteri Ref</dt><dd>{val(record.customer_ref)}</dd><dt>Sistem Kodu</dt><dd>{val(record.system_code)}</dd><dt>Ürün Tanımı</dt><dd>{val(record.product_name)}</dd><dt>Ambalaj Tipi</dt><dd>{val(record.packaging_type)}</dd><dt>Toplam Ağırlık</dt><dd>{num(record.total_weight_g)} g</dd></dl></section>
      <section className="card full"><h2>PPWR Kayıt Durumu / Record Status</h2><div className="statusgrid"><div className="check"><b>Ambalaj Kimliği</b><small>İş, müşteri ve sistem kodları bağlı.</small><div className={`flag ${statusClass(record.identity_status)}`}>● {val(record.identity_status)}</div></div><div className="check"><b>Teknik Dokümantasyon</b><small>Annex VII dosya seti ve kanıtlar.</small><div className={`flag ${statusClass(record.technical_status)}`}>● {val(record.technical_status)}</div></div><div className="check"><b>EU Declaration of Conformity</b><small>Annex VIII model yapısı.</small><div className={`flag ${statusClass(record.declaration_status)}`}>● {val(record.declaration_status)}</div></div></div></section>
      <section className="card"><h2>Ambalaj Parçaları / Packaging Components</h2>{components.length ? components.map((c,i)=><div className="component" key={i}><div className="num">{String(i+1).padStart(2,"0")}</div><div><h3>{val(c.name)}</h3><p>{[c.material,c.spec,c.function].filter(Boolean).join(" · ")}</p></div><div className="weight">{val(c.weight_g)} g</div></div>) : <p className="muted">Komponent bilgisi girilmemiş.</p>}<div className="component-total"><strong>Toplam / Total</strong><strong>{num(record.total_weight_g)} g</strong></div></section>
      <section className="card"><h2>Malzeme Bileşimi / Material Composition</h2><div className="table-scroll"><table className="materials"><thead><tr><th>Malzeme</th><th>Ağırlık</th><th>Oran</th></tr></thead><tbody>{materials.length ? materials.map((m,i)=><tr key={i}><td>{val(m.material)}</td><td>{val(m.weight_g)} g</td><td>{val(m.ratio_percent)}%</td></tr>) : <tr><td colSpan="3">Malzeme verisi girilmemiş.</td></tr>}</tbody></table></div></section>
      <section className="card full"><h2>Belgeler / Documents</h2>{record.declaration_pdf_url && <div className="doc"><div className="docicon">PDF</div><div><h3>EU Declaration of Conformity</h3><p>{val(record.declaration_id)}</p></div><div className="actions"><a className="btn" href={record.declaration_pdf_url} target="_blank" rel="noreferrer">Görüntüle</a><a className="btn primary" href={record.declaration_pdf_url} download>PDF İndir</a></div></div>}{record.technical_pdf_url && <div className="doc"><div className="docicon">PDF</div><div><h3>Packaging Technical File Summary</h3><p>Teknik dosya / ambalaj kimliği</p></div><div className="actions"><a className="btn" href={record.technical_pdf_url} target="_blank" rel="noreferrer">Görüntüle</a><a className="btn primary" href={record.technical_pdf_url} download>PDF İndir</a></div></div>}{!record.declaration_pdf_url && !record.technical_pdf_url && <p className="muted">Yayınlanmış belge bulunmuyor.</p>}</section>
      <section className="card full"><h2>Ürün Görseli / Product Visualization</h2><div className="visual"><div><dl className="info"><dt>Görsel Kaynağı</dt><dd>Üretim / CAD / Kalite</dd><dt>Revizyon Bağı</dt><dd>{val(record.revision_no)}</dd><dt>Erişim</dt><dd>Kamu PPWR kaydı</dd></dl></div><div className="package">{record.product_image_url ? <img className="product-image" src={record.product_image_url} alt={record.product_name || "Ambalaj görseli"} /> : <div className="image-placeholder">Ürün görseli eklenmemiş</div>}</div></div></section>
    </div>
    <div className="footer"><strong>{COMPANY.name}</strong><br/>{COMPANY.address} · {COMPANY.email} · {COMPANY.phone}<br/><span>PPWR belge erişimi ve ambalaj kayıt sistemi</span></div>
  </div>;
}
